name: "Execute Listing"

env:
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_EMAIL: "${{ github.actor }}@users.noreply.github.com"

on:
  workflow_dispatch:
    inputs:
      listing:
        type: string
        description: 'Listing number (e.g. 2.1)'
        required: true

jobs:
  execute-listing:
    name: "Executing listing ${{ github.event.inputs.listing }}"
    runs-on: ubuntu-latest
    steps:
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.7

      - name: Install Protoc Dependencies
        run: |
          sudo apt-get install -y protobuf-compiler golang-goprotobuf-dev
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      # Go build cache
      - name: Go Build Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      - name: Find and Execute Listing Script
        run: |
          # Find the directory for the specified listing
          LISTING_DIR=$(find . -type d -name "listing_${{ github.event.inputs.listing }}" | head -n 1)

          # Check if the directory exists
          if [ -z "$LISTING_DIR" ]; then
            echo "Error: Listing directory 'listing_${{ github.event.inputs.listing }}' not found."
            exit 1
          fi

          # Change to the listing directory
          cd "$LISTING_DIR"

          # Ensure run.sh exists and is executable
          if [ ! -x "./run.sh" ]; then
            echo "Error: run.sh not found or not executable in $LISTING_DIR."
            exit 1
          fi

          # Execute the run.sh script with GitHub username and email as arguments
          ./run.sh ${{ env.GITHUB_USERNAME }} ${{ env.GITHUB_EMAIL }}
          

